services:
  air-sensor:
    build:
      context: .
    privileged: true
    volumes:
      - ./air_sensor.py:/usr/src/app/air_sensor.py
      - ./main.py:/usr/src/app/main.py
    command: python -u main.py

  web-server:
    build:
      context: .
    privileged: true
    volumes:
      - ./air_sensor.py:/usr/src/app/air_sensor.py
      - ./webserver.py:/usr/src/app/webserver.py
      - ./touch_sensor.py:/usr/src/app/touch_sensor.py
      - ./light_sensor.py:/usr/src/app/light_sensor.py
    ports:
      - 8080:8080
    command: python -u webserver.py