services:
  air-sensor:
    build:
      context: .
    privileged: true
    volumes:
      - ./air_sensor.py:/usr/src/app/air_sensor.py
      - ./main.py:/usr/src/app/main.py
    command: python -u main.py

  touch-sensor:
    build:
      context: .
    privileged: true
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
    volumes:
      - "/sys:/sys"   # mount full sysfs, not just /sys/class/gpio
      - "./touch_sensor.py:/usr/src/app/touch_sensor.py"
    command: python -u touch_sensor.py

  web-server:
    build:
      context: .
    privileged: true
    volumes:
      - ./air_sensor.py:/usr/src/app/air_sensor.py
      - ./webserver.py:/usr/src/app/webserver.py
    ports:
      - 8080:8080
    command: python -u webserver.py